import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { MENU_PROMPT } from './menuPrompt.ts'
import { MenuDocSchema } from './menuSchema.ts'

/*
 * Exactly what `pnpm gen:schema` writes into `docs/`. The generator and the
 * drift test both go through here, so "the file on disk is stale" is the only
 * way they can disagree — never "the two rendered it differently".
 *
 * Server-side only: it pulls in zod, and `node:url` besides.
 */

const docsFile = (name: string): string =>
  fileURLToPath(new URL(`../../docs/${name}`, import.meta.url))

export const schemaFile = (): string => docsFile('menu.schema.json')
export const promptFile = (): string => docsFile('menu-prompt.md')

/**
 * `io: 'input'` is the important flag: it renders a field with a `.default()`
 * as optional-with-a-default rather than required, which is exactly what an
 * agent writing a document needs to see.
 */
export const renderedSchema = (): string =>
  `${JSON.stringify(z.toJSONSchema(MenuDocSchema, { io: 'input' }), null, 2)}\n`

export const renderedPrompt = (): string =>
  `<!-- Generated by \`pnpm gen:schema\` from src/shared/menuPrompt.ts. Do not edit. -->\n\n` +
  '```text\n' +
  `${MENU_PROMPT.trimEnd()}\n` +
  '```\n'
